const map = [
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "grass", "isBarrier": false, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
  [
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
    { "tile": "rock", "isBarrier": true, "objects": [] },
  ],
];

export default map;